name: Tests

on:
  push:
    tags:
      - '*'
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - id: get-current-tag
        uses: zingimmick/github-action-get-current-tag@v1

      - name: Print tag
        run: echo "${{ steps.get-current-tag.outputs.tag }}"
